#! /bin/bash
tunnel-testinfra() {
  aws ssm start-session --target i-029964e4ea03bc32d \
  --document-name AWS-StartPortForwardingSessionToRemoteHost \
  --parameters '{"portNumber":["5432"],"localPortNumber":["6003"],"host":["ps-testinfra-mi-db.c1a3u3ehyoj2.us-east-1.rds.amazonaws.com"]}'
}
tunnel-testinfra