#! /bin/bash
tunnel-prod() {
  	aws ssm start-session --target i-0e33468b463fa029e \
    	--document-name AWS-StartPortForwardingSessionToRemoteHost \
    	--parameters '{"portNumber":["5432"],"localPortNumber":["6002"],"host":["ps-prod-mi-db.c1a3u3ehyoj2.us-east-1.rds.amazonaws.com"]}'
}
tunnel-prod