#! /bin/bash
tunnel-qa-ltr() {
	  aws ssm start-session --target i-07360909d89460b5f \
    	--document-name AWS-StartPortForwardingSessionToRemoteHost \
    	--parameters '{"portNumber":["5432"],"localPortNumber":["5434"],"host":["psqapg.c1a3u3ehyoj2.us-east-1.rds.amazonaws.com"]}'
}
tunnel-qa-ltr