#! /bin/bash
tunnel-rc-ltr() {
	  aws ssm start-session --target i-0578275aea43ec1c2 \
    	--document-name AWS-StartPortForwardingSessionToRemoteHost \
    	--parameters '{"portNumber":["5432"],"localPortNumber":["5436"],"host":["psrcpg.c1a3u3ehyoj2.us-east-1.rds.amazonaws.com"]}'
}
tunnel-rc-ltr