#! /bin/bash
tunnel-qa() {
	aws ssm start-session --target i-07360909d89460b5f \
    	--document-name AWS-StartPortForwardingSessionToRemoteHost \
    	--parameters '{"portNumber":["5432"],"localPortNumber":["5433"],"host":["ps-qa-mi-db.c1a3u3ehyoj2.us-east-1.rds.amazonaws.com"]}'
}
tunnel-qa